import crypto from "crypto";
import { env } from "../config/env.js";
import { AppError } from "../utils/app-error.js";
import { HTTP_STATUS } from "../constants/http-status.js";
import { logger } from "../utils/logger.js";

interface CreateRazorpayOrderInput {
  amountInPaise: number;
  currency?: string;
  receipt?: string;
  notes?: Record<string, string>;
}

interface RazorpayOrderResponse {
  id: string;
  entity: string;
  amount: number;
  amount_paid: number;
  amount_due: number;
  currency: string;
  receipt?: string;
  status: string;
  attempts: number;
  notes: Record<string, string>;
  created_at: number;
}

interface VerifyRazorpaySignatureInput {
  razorpayOrderId: string;
  razorpayPaymentId: string;
  razorpaySignature: string;
}

/**
 * Verifies the cryptographic HMAC SHA-256 signature generated by Razorpay Checkout.
 */
export const verifyRazorpaySignature = ({
  razorpayOrderId,
  razorpayPaymentId,
  razorpaySignature,
}: VerifyRazorpaySignatureInput): boolean => {
  const secret = env.RAZORPAY_KEY_SECRET;
  if (!secret) {
    logger.error("RAZORPAY_KEY_SECRET is not configured in environment");
    throw new AppError(
      "Payment gateway configuration error",
      HTTP_STATUS.INTERNAL_SERVER_ERROR,
    );
  }

  if (!razorpayOrderId || !razorpayPaymentId || !razorpaySignature) {
    return false;
  }

  const generatedSignature = crypto
    .createHmac("sha256", secret)
    .update(`${razorpayOrderId}|${razorpayPaymentId}`)
    .digest("hex");

  // Constant-time comparison to protect against timing attacks
  const expectedBuffer = Buffer.from(generatedSignature, "utf8");
  const actualBuffer = Buffer.from(razorpaySignature, "utf8");

  if (expectedBuffer.length !== actualBuffer.length) {
    return false;
  }

  return crypto.timingSafeEqual(expectedBuffer, actualBuffer);
};

/**
 * Creates a gateway order in Razorpay for checkout initiation.
 */
export const createRazorpayGatewayOrder = async ({
  amountInPaise,
  currency = "INR",
  receipt,
  notes,
}: CreateRazorpayOrderInput): Promise<RazorpayOrderResponse> => {
  const keyId = env.RAZORPAY_KEY_ID;
  const keySecret = env.RAZORPAY_KEY_SECRET;

  if (!keyId || !keySecret) {
    throw new AppError(
      "Razorpay API credentials are not configured",
      HTTP_STATUS.INTERNAL_SERVER_ERROR,
    );
  }

  const authHeader = `Basic ${Buffer.from(`${keyId}:${keySecret}`).toString("base64")}`;

  try {
    const response = await fetch("https://api.razorpay.com/v1/orders", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: authHeader,
      },
      body: JSON.stringify({
        amount: Math.round(amountInPaise),
        currency,
        receipt: receipt || `rcpt_${Date.now()}`,
        notes: notes || {},
      }),
    });

    const data = (await response.json()) as RazorpayOrderResponse & {
      error?: { description?: string };
    };

    if (!response.ok) {
      logger.error(
        { status: response.status, error: data.error },
        "Failed to create Razorpay gateway order",
      );
      throw new AppError(
        data.error?.description || "Failed to create payment order with gateway",
        HTTP_STATUS.BAD_REQUEST,
      );
    }

    return data;
  } catch (error) {
    if (error instanceof AppError) throw error;
    logger.error({ err: error }, "Error connecting to Razorpay API");
    throw new AppError(
      "Unable to connect to payment gateway",
      HTTP_STATUS.INTERNAL_SERVER_ERROR,
    );
  }
};

/**
 * Fetches payment details directly from Razorpay API.
 */
export const fetchRazorpayPayment = async (paymentId: string) => {
  const keyId = env.RAZORPAY_KEY_ID;
  const keySecret = env.RAZORPAY_KEY_SECRET;

  if (!keyId || !keySecret) {
    throw new AppError(
      "Razorpay API credentials are not configured",
      HTTP_STATUS.INTERNAL_SERVER_ERROR,
    );
  }

  const authHeader = `Basic ${Buffer.from(`${keyId}:${keySecret}`).toString("base64")}`;

  try {
    const response = await fetch(`https://api.razorpay.com/v1/payments/${paymentId}`, {
      method: "GET",
      headers: {
        Authorization: authHeader,
      },
    });

    if (!response.ok) {
      const data = (await response.json()) as { error?: { description?: string } };
      logger.error(
        { status: response.status, error: data.error },
        "Failed to fetch payment details from Razorpay",
      );
      throw new AppError(
        data.error?.description || "Invalid or unrecognized payment ID",
        HTTP_STATUS.BAD_REQUEST,
      );
    }

    return (await response.json()) as {
      id: string;
      status: string;
      amount: number;
      currency: string;
      order_id?: string;
    };
  } catch (error) {
    if (error instanceof AppError) throw error;
    logger.error({ err: error, paymentId }, "Error querying payment from Razorpay API");
    throw new AppError(
      "Unable to verify payment with gateway",
      HTTP_STATUS.INTERNAL_SERVER_ERROR,
    );
  }
};
